### ISSUE TITLE
Kompatiblität mit Eclipse und Newssystem

### ISSUE THREAD

**Issue by cgpro** [timgatzky/pct_image_crop#10]
Kann es sein das die Erweiterung mit den News nicht funktioniert bzw. muss noch was eingestellt werden? Bei Lister- und Readerseiten bekomme ich immer folgenden Fehler:
Type error: Argument 1 passed to Contao\Model::isPreviewMode() must be of the type array, null given, called in /var/virtual/schupfinger/public/dev/chinabrand/vendor/contao/comments-bundle/src/Resources/contao/models/CommentsModel.php on line 149

Wenn ich image_crop deaktiviere gehts wieder.

**Comment by timgatzky** [comment]
Mhh... wüsste jetzt nicht was die Kommentare hier wollen. Ich hab es aber auch nicht in News getestet. Schau ich mir mal an.

**Comment by timgatzky** [comment]
Ich hab es in 3.5 in den News getestet (Detailseite), das passt.

**Comment by cgpro** [comment]
Ok, dann scheint das nur bei mir zu sein.
